import React, { useState } from 'react';
import { useForm, FormProvider } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { useNavigate } from 'react-router-dom';
import { toast } from 'react-hot-toast';
import { Activity, AlertCircle, Save } from 'lucide-react';

import { vitalSchema } from '../../validators/vital.validator';
import { FormInput } from '../ui/forms/Form';
import { useRecordVital, useUpdateVital } from '../../hooks/useVitals';

export const VitalForm = ({ initialData, isEdit = false }) => {
  const navigate = useNavigate();
  const [apiError, setApiError] = useState(null);

  const recordVitalMutation = useRecordVital();
  const updateVitalMutation = useUpdateVital();

  const methods = useForm({
    resolver: zodResolver(vitalSchema),
    defaultValues: {
      heartRate: initialData?.heartRate || 72,
      spo2: initialData?.spo2 || 98,
      temperature: initialData?.temperature || 36.8,
      systolicBp: initialData?.systolicBp || 120,
      diastolicBp: initialData?.diastolicBp || 80,
      glucose: initialData?.glucose || '',
      weightKg: initialData?.weightKg || '',
      heightCm: initialData?.heightCm || '',
      recordedAt: initialData?.recordedAt ? new Date(initialData.recordedAt).toISOString().slice(0, 16) : '',
    },
    mode: 'onChange',
  });

  const onSubmit = async (values) => {
    setApiError(null);

    const payload = {
      heartRate: Number(values.heartRate),
      spo2: Number(values.spo2),
      temperature: Number(values.temperature),
      systolicBp: Number(values.systolicBp),
      diastolicBp: Number(values.diastolicBp),
      ...(values.glucose ? { glucose: Number(values.glucose) } : {}),
      ...(values.weightKg ? { weightKg: Number(values.weightKg) } : {}),
      ...(values.heightCm ? { heightCm: Number(values.heightCm) } : {}),
      ...(values.recordedAt ? { recordedAt: new Date(values.recordedAt).toISOString() } : {}),
    };

    try {
      if (isEdit && initialData?.id) {
        await updateVitalMutation.mutateAsync({ id: initialData.id, data: payload });
        toast.success('Vital record updated successfully!');
      } else {
        await recordVitalMutation.mutateAsync(payload);
        toast.success('Vital record saved successfully!');
      }
      navigate('/vitals');
    } catch (err) {
      console.error('Vital form submission error:', err);
      const message = err.message || 'Failed to save vital record. Please check your inputs.';
      setApiError(message);
      toast.error(message);
    }
  };

  const isSubmitting = recordVitalMutation.isPending || updateVitalMutation.isPending;

  return (
    <FormProvider {...methods}>
      <form onSubmit={methods.handleSubmit(onSubmit)} className="space-y-6">
        {apiError && (
          <div className="p-3.5 rounded-xl bg-rose-500/10 border border-rose-500/30 text-rose-600 text-sm flex items-start space-x-2.5">
            <AlertCircle className="w-5 h-5 shrink-0 mt-0.5" />
            <span>{apiError}</span>
          </div>
        )}

        <div className="bg-card border border-border/60 rounded-3xl p-6 sm:p-8 shadow-sm space-y-6">
          <div className="flex items-center space-x-3 border-b border-border/50 pb-4">
            <div className="w-10 h-10 rounded-xl bg-primary/10 text-primary flex items-center justify-center font-bold">
              <Activity className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-base font-bold text-foreground font-display">
                {isEdit ? 'Edit Vital Record' : 'Record Vital Telemetry'}
              </h3>
              <p className="text-xs text-muted-foreground">
                Enter your current health measurements. BMI and triage alerts will be generated by the backend.
              </p>
            </div>
          </div>

          {/* Primary Vitals Grid */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <FormInput name="heartRate" label="Heart Rate (BPM) *" type="number" placeholder="72" />
            <FormInput name="spo2" label="Oxygen Saturation SpO2 (%) *" type="number" placeholder="98" />
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <FormInput name="systolicBp" label="Systolic BP (mmHg) *" type="number" placeholder="120" />
            <FormInput name="diastolicBp" label="Diastolic BP (mmHg) *" type="number" placeholder="80" />
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <FormInput name="temperature" label="Body Temperature (°C) *" type="number" step="0.1" placeholder="36.8" />
            <FormInput name="glucose" label="Blood Glucose (mg/dL) [Optional]" type="number" placeholder="100" />
          </div>

          {/* Body Measurements & Custom Date */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 pt-2 border-t border-border/40">
            <FormInput name="weightKg" label="Weight (kg) [Optional]" type="number" step="0.1" placeholder="70.5" />
            <FormInput name="heightCm" label="Height (cm) [Optional]" type="number" step="0.1" placeholder="175.0" />
            <FormInput name="recordedAt" label="Recorded Date & Time [Optional]" type="datetime-local" />
          </div>

          {/* Submit Button */}
          <div className="pt-4 border-t border-border/50 flex items-center justify-end space-x-3">
            <button
              type="button"
              onClick={() => navigate('/vitals')}
              className="px-4 py-2 bg-accent text-accent-foreground text-xs font-semibold rounded-xl hover:bg-accent/80 transition-colors"
            >
              Cancel
            </button>

            <button
              type="submit"
              disabled={isSubmitting}
              className="px-6 py-2.5 bg-primary text-primary-foreground text-xs font-bold rounded-xl hover:bg-primary/90 shadow-lg shadow-primary/25 disabled:opacity-50 transition-all flex items-center space-x-2"
            >
              {isSubmitting ? (
                <div className="w-4 h-4 border-2 border-primary-foreground/30 border-t-primary-foreground rounded-full animate-spin" />
              ) : (
                <>
                  <span>{isEdit ? 'Update Vital Entry' : 'Save Vital Record'}</span>
                  <Save className="w-4 h-4" />
                </>
              )}
            </button>
          </div>
        </div>
      </form>
    </FormProvider>
  );
};

export default VitalForm;
