import { ROLES } from './roles';

export const PERMISSIONS = {
  VIEW_DASHBOARD: [ROLES.ADMIN, ROLES.DOCTOR, ROLES.PATIENT],
  MANAGE_APPOINTMENTS: [ROLES.DOCTOR, ROLES.PATIENT],
  VIEW_VITALS: [ROLES.DOCTOR, ROLES.PATIENT],
  MANAGE_VITALS: [ROLES.PATIENT],
  MANAGE_AVAILABILITY: [ROLES.DOCTOR],
  VIEW_DOCTORS: [ROLES.ADMIN, ROLES.PATIENT],
  VIEW_PATIENTS: [ROLES.ADMIN, ROLES.DOCTOR],
  ADMIN_SETTINGS: [ROLES.ADMIN],
};

export default PERMISSIONS;
